---
- name: "(ansible_role_base-repos) Install repo keys"
  apt_key:
    url: "{{ item.value.key_url }}"
    id: "{{ item.value.key_id }}"
    state: present
  loop: "{{ query('dict', apt) }}"

- name: "(ansible_role_base-repos) Install repos"
  apt_repository:
    repo: "deb {{ item.value.repo_url }} {{ item.value.repo_release }} {{ item.value.repo_component }}"
    state: present
  loop: "{{ query('dict', apt) }}"
