---
# tasks file for ansible_role_base

- name: "(ansible_role_base) Set required vars and facts"
  block:
    - name: "(ansible_role_base) Read vars"
      changed_when: false
      check_mode: false
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}-{{ ansible_distribution_version }}.yml'
            - '{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml'
            - '{{ ansible_distribution | lower }}.yml'
          paths:
            - 'vars'
      tags:
        - vars
        - set_vars

    - name: "(ansible_role_base) Check if running in AWS"
      uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      check_mode: false
      failed_when: false
      tags:
        - aws
        - check_aws

    - name: "(ansible_role_base) Set is_aws fact"
      set_fact:
        is_aws: "{{ (aws_uri_check.status == 200) | ternary(true, false, false) }}"
      tags:
        - aws
        - check_aws

    - name: "(ansible_role_base) Update/Upgrade Default Packages"
      block:
        # - name: "(ansible_role_base) Create apt daily update/upgrade override dirs"
        #   file:
        #     path: "/etc/systemd/system/{{ item }}.timer.d"
        #     state: directory
        #     mode: 0755
        # - name: "(ansible_role_base) Create apt daily update/upgrade override configs"
        #   template:
        #     src: apt-daily-override.conf.j2
        #     path: "/etc/systemd/system/{{ item }}.timer.d/override.conf"
        #     owner: root
        #     group: root
        #     mode: 0644
        #   loop:
        #     - "apt-daily"
        #     - "apt-daily-upgrade"
        #   when:
        #     - "ansible_service_mgr == 'systemd'"

        - name: "(ansible_role_base) Update Base Debian Packages"
          apt:
            update_cache: true
            upgrade: 'yes'
          when:
            - ansible_facts['os_family'] == 'Debian'
      when:
        - update_default_packages is defined
        - update_default_packages

    - name: "(ansible_role_base) Get Installed Packages"
      package_facts:
      when: get_package_facts
  tags:
    - always

- name: "(ansible_role_base) Include Repo Install Task"
  include_tasks: repos.yml
  when: repo_install
  tags:
    - repo
    - repos

- name: "(ansible_role_base) Include Package Install Task"
  include_tasks: packages.yml
  when: install_default_packages
  tags:
    - package
    - packages

- name: "(ansible_role_base) Find latest release of restic"
  community.general.github_release:
    user: restic
    repo: restic
    action: latest_release
  register: restic_latest

- name: "(ansible_role_base) Download latest release of restic"
  get_url:
    url: "https://github.com/restic/restic/releases/download/v{{ restic_latest }}/restic_{{ restic_latest }}_linux_arm64.bz2"
    dest: "/var/tmp/restic.bz2"

- name: "(ansible_role_base) Uncompress restic"
  command:
    cmd: bunzip2 /var/tmp/restic.bz2
    creates: /var/tmp/restic

- name: "(ansible_role_base) Install restic"
  become: true
  copy:
    src: /var/tmp/restic
    dest: /usr/local/bin/restic
    remote_src: true
    owner: root
    group: root
    mode: '0755'

- name: "(ansible_role_base) Find latest release of rclone"
  community.general.github_release:
    user: rclone
    repo: rclone
    action: latest_release
  register: rclone_latest

- name: "(ansible_role_base) Install latest release of rclone"
  apt:
    deb: "https://github.com/rclone/rclone/releases/download/v{{ rclone_latest }}/rclone-v{{ rclone_latest }}-linux-arm64.deb"
  register: rclone_result
  until: rclone_result is succeeded
  delay: 5
  retries: 5

- name: "(ansible_role_base) Find latest release of telegraf"
  community.general.github_release:
    user: influxdata
    repo: telegraf
    action: latest_release
  register: telegraf_latest

- name: "(ansible_role_base) Install latest release of telegraf"
  apt:
    deb: "https://dl.influxdata.com/telegraf/releases/telegraf_{{ telegraf_latest }}_arm64.deb"
  register: telegraf_result
  until: telegraf_result is succeeded
  delay: 5
  retries: 5

- name: "(ansible_role_base) Include SSH Configuration Task"
  include_tasks: ssh.yml
  when: ssh_config

- name: "(ansible_role_base) Install support files and scripts"
  include_tasks: support_files.yml
