---
# Specify the uid and gid to ensure they match what
# will be set in the mount point
- name: "(ansible_role_base) Create minecraft group"
  become: true
  group:
    gid: 1001
    name: minecraft
    state: present

- name: "(ansible_role_base) Create minecraft user"
  become: true
  user:
    uid: 1001
    name: mcuser
    group: minecraft
    shell: /usr/bin/bash
    state: present

- name: "(ansible_role_base) Add ubuntu user to minecraft group"
  become: true
  user:
    name: ubuntu
    groups: minecraft
    append: true

- name: "(ansible_role_base) Install support files"
  become: true
  copy:
    src: '{{ item }}'
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: minecraft
    mode: '0750'
  loop:
    - rclone_backup.sh
    - restic_backup.sh
    - restic_setup.sh
    - minecraft_restore.sh

- name: "(ansible_role_base) Install minecraft service"
  become: true
  copy:
    src: minecraft.service
    dest: /etc/systemd/system/minecraft.service
    owner: root
    group: root
    mode: '0644'

- name: "(ansible_role_base) Reload systemd"
  become: true
  systemd:
    daemon_reload: true

- name: "(ansible_role_base) Enable minecraft service"
  become: true
  systemd:
    name: minecraft
    enabled: true
    state: stopped

- name: "(ansible_role_base) Install hourly backup cronjob"
  become: true
  copy:
    src: bifrost-hourly-backup
    dest: /etc/cron.hourly/bifrost-hourly-backup
    owner: root
    group: root
    mode: '0750'

- name: "(ansible_role_base) Install daily backup cronjob"
  become: true
  copy:
    src: bifrost-daily-sync
    dest: /etc/cron.hourly/bifrost-daily-sync
    owner: root
    group: root
    mode: '0755'

- name: "(ansible_role_base) Install xterm-kitty terminfo"
  become: true
  copy:
    src: xterm-kitty
    dest: /usr/share/terminfo/x/xterm-kitty
    owner: root
    group: root
    mode: '0644'
