---

- name: AWS Configuration
  hosts: tag_Minecraft
  vars:
    ansible_port: 44390
    ansible_user: ubuntu
    ansible_sftp_extra_args: '-P 44390'

  tasks:
    - name: "(Minecraft) Create ops file"
      become: true
      copy:
        dest: /srv/minecraft/ops.json
        content: "{{ ops | to_nice_json }}"
        owner: mcuser
        group: minecraft

    - name: "(Minecraft) Create whitelist file"
      become: true
      copy:
        dest: /srv/minecraft/whitelist.json
        content: "{{ whitelist | to_nice_json }}"
        owner: mcuser
        group: minecraft

    - name: "(Minecraft) Create eula.txt file"
      become: true
      copy:
        dest: /srv/minecraft/eula.txt
        content: "eula=true"
        owner: mcuser
        group: minecraft

    - name: "(Minecraft) Deploy server.properties"
      become: true
      template:
        src: "server.properties.j2"
        dest: /srv/minecraft/server.properties
        owner: mcuser
        group: minecraft
        mode: '0644'
      tags:
        - properties

    - name: "(Minecraft) Deploy Terraforged config"
      become: true
      copy:
        src: terraforged-generator.json
        dest: /srv/minecraft/config/terraforged/terraforged-generator.json
        owner: mcuser
        group: minecraft
        mode: '0644'

    - name: "(Minecraft) Deploy Default Waystone configuration"
      become: true
      copy:
        src: waystones-server.toml
        dest: /srv/minecraft/defaultconfigs/waystones-server.toml
        owner: mcuser
        group: minecraft
        mode: '0644'

    - name: "(Minecraft) Deploy restic exclusions configuration"
      become: true
      copy:
        src: restic_excludes.txt
        dest: /srv/minecraft/restic_excludes.txt
        owner: mcuser
        group: minecraft
        mode: '0644'

    - name: "(Minecraft) Deploy Minecraft startup script"
      become: true
      copy:
        src: minecraft_server-run.sh
        dest: /srv/minecraft/minecraft_server-run.sh
        owner: mcuser
        group: minecraft
        mode: '0755'

    - name: "(Minecraft) Deploy Minecraft systemd unitfile"
      become: true
      copy:
        src: minecraft.service
        dest: /etc/systemd/system/minecraft.service
        owner: root
        group: root
        mode: '0644'

    - name: "(Minecraft) Deploy yardboss service"
      become: true
      template:
        src: "yardboss.service.j2"
        dest: /etc/systemd/system/server.properties
        owner: root
        group: root
        mode: '0644'

    - name: "(Minecraft) Reload systemd"
      become: true
      systemd:
        daemon_reload: true

    - name: "(Minecraft) Enable minecraft at boot"
      become: true
      systemd:
        name: minecraft
        enabled: true

    - name: "(Minecraft) Enable yardboss at boot"
      become: true
      systemd:
        name: yardboss
        enabled: true

    - name: "(Minecraft) Deploy minecraft shared resources"
      become: true
      copy:
        src: "{{ item }}"
        dest: "/usr/local/share/minecraft/{{ item }}"
        owner: root
        group: minecraft
        mode: '0644'
      loop:
        - create_rclone_volume.yaml
        - msg_template.json

    - name: "(Minecraft) Deploy backup scripts"
      become: true
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: minecraft
        mode: '0755'
      loop:
        - restic_backup.sh
        - restic_setup.sh
        - minecraft_restore.sh
        - rclone_backup.sh

    - name: "(Minecraft) Deploy restic password command"
      become: true
      copy:
        src: fetch_restic_pass.sh
        dest: /usr/local/bin/fetch_restic_pass.sh
        owner: mcuser
        group: minecraft
        mode: '0755'

    - name: "(Minecraft) Create rclone backup path"
      become: true
      file:
        path: /mnt/rclone_local
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "(Minecraft) Setup fstab for rclone"
      ansible.posix.mount:
        path: /mnt/rclone_local
        src: LABEL=rclone_tmp
        fstype: xfs
        opts: noauto,user,defaults,nodiratime,noatime,comment=rclone_backup
        state: present
